const json = `
{
  "type": "COMPOUND",
  "name": "",
  "value": [{
    "type": "COMPOUND",
    "name": "Data",
    "value": [{
      "type": "LONG",
      "name": "LastPlayed",
      "value": "1541085962226"
    }, {
      "type": "LONG",
      "name": "RandomSeed",
      "value": "7833597690052327928"
    }, {
      "type": "COMPOUND",
      "name": "Player",
      "value": [{
        "type": "LIST",
        "name": "Motion",
        "value": [{
          "type": "DOUBLE",
          "value": 1.4104119838762753e-18
        }, {
          "type": "DOUBLE",
          "value": -0.0784000015258789
        }, {
          "type": "DOUBLE",
          "value": 1.0919785511256983e-18
        }]
      }, {
        "type": "SHORT",
        "name": "Health",
        "value": 20
      }, {
        "type": "SHORT",
        "name": "Air",
        "value": 300
      }, {
        "type": "BYTE",
        "name": "OnGround",
        "value": 1
      }, {
        "type": "LIST",
        "name": "Rotation",
        "value": [{
          "type": "FLOAT",
          "value": -3652.691650390625
        }, {
          "type": "FLOAT",
          "value": 13.350007057189941
        }]
      }, {
        "type": "FLOAT",
        "name": "FallDistance",
        "value": 0
      }, {
        "type": "INT",
        "name": "Score",
        "value": 0
      }, {
        "type": "LIST",
        "name": "Pos",
        "value": [{
          "type": "DOUBLE",
          "value": -611.8875563595599
        }, {
          "type": "DOUBLE",
          "value": 81.62000000476837
        }, {
          "type": "DOUBLE",
          "value": -347.483825753181
        }]
      }, {
        "type": "SHORT",
        "name": "DeathTime",
        "value": 0
      }, {
        "type": "SHORT",
        "name": "Fire",
        "value": -20
      }, {
        "type": "SHORT",
        "name": "HurtTime",
        "value": 0
      }, {
        "type": "SHORT",
        "name": "AttackTime",
        "value": 0
      }, {
        "type": "LIST",
        "name": "Inventory",
        "value": [{
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 0
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 3
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 64
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 1
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 3
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 64
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 2
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 277
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 1
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": -32355
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 3
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 50
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 1
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 4
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 20
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": -37
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 5
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 278
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 1
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": -32608
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 6
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 276
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 1
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": -32657
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 7
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 44
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 3
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 8
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 263
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 16
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 9
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 318
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 3
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 10
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 37
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 3
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 11
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 3
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 64
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 12
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 3
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 64
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 13
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 4
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 13
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 14
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 13
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 2
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 15
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 3
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 22
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 30
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 274
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 1
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 1
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 31
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 270
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 1
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 11
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 34
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 54
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": -2
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": 0
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 100
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 313
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 1
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": -32657
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 101
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 312
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 1
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": -32657
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 102
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 311
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 1
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": -32657
          }]
        }, {
          "type": "COMPOUND",
          "value": [{
            "type": "BYTE",
            "name": "Slot",
            "value": 103
          }, {
            "type": "SHORT",
            "name": "id",
            "value": 310
          }, {
            "type": "BYTE",
            "name": "Count",
            "value": 1
          }, {
            "type": "SHORT",
            "name": "Damage",
            "value": -32657
          }]
        }]
      }]
    }, {
      "type": "INT",
      "name": "SpawnY",
      "value": 64
    }, {
      "type": "INT",
      "name": "SpawnZ",
      "value": -408
    }, {
      "type": "BYTE",
      "name": "SnowCovered",
      "value": 0
    }, {
      "type": "INT",
      "name": "SpawnX",
      "value": -623
    }, {
      "type": "LONG",
      "name": "Time",
      "value": "38286"
    }, {
      "type": "LONG",
      "name": "SizeOnDisk",
      "value": "3508208"
    }]
  }]
}
`

export default JSON.parse(json)
